AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  Env:
    Type: String
    AllowedValues: ['dev', 'test', 'prod']
    Default: 'dev'

resources:
  "cloudfront":
    Type: AWS::CloudFront::Distribution
    Properties: 
      DistributionConfig: 
        DistributionConfig
      Tags: 
        - Tag

  "bucket":
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: my-s3-bucket
      Tags: 
        - Tag
      VersioningConfiguration: 
        VersioningConfiguration
      WebsiteConfiguration: 
          ErrorDocument: String
          IndexDocument: String
          RedirectAllRequestsTo: 
            RedirectAllRequestsTo
          RoutingRules: 
            - RoutingRule

