AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  Env:
    Type: String
    AllowedValues: ['dev', 'test', 'prod']
    Default: 'dev'
  Reg:
    Type: String
    AllowedValues: ['eu-central-1', 'us-east-1', 'us-west-1']
    Default: 'eu-central-1'

Resources:
  "cloudfront":
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !Sub s3-bucket-tech-week-2-awsome.s3.${Reg}.amazonaws.com
            Id: s3-bucket-tech-week-2-awsome
            S3OriginConfig:
              OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${CloudFrontOriginIdentity}'
        Enabled: 'true'
        Comment: Some comment
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          TargetOriginId: s3-bucket-tech-week-2-awsome
          ForwardedValues:
            QueryString: 'false'
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
        ViewerCertificate:
          CloudFrontDefaultCertificate: 'true'

  "CloudFrontOriginIdentity":
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: 'origin identity'

  "bucket":
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: s3-bucket-tech-week-2-awsome
      VersioningConfiguration: 
          Status: Enabled
      WebsiteConfiguration: 
          IndexDocument: !Sub 
            - '${Environment}.html'
            - Environment: !Ref Env


    "BucketPolicy":
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: s3-bucket-tech-week-2-awsome
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Action: 's3:GetObject' 
              Effect: Allow
              Principal:
                AWS: !Sub 'arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${CloudFrontOriginIdentity}'
              Resource: arn:aws:s3:::s3-bucket-tech-week-2-awsome/*