AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  Env:
    Type: String
    AllowedValues: ['dev', 'test', 'prod']
    Default: 'dev'
  Reg:
    Type: String
    AllowedValues: ['eu-central-1', 'us-east-1', 'us-west-1']
    Default: 'eu-central-1'


Resources:
  "bucket":
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: s3-bucket-tech-week-2-awsome2
      VersioningConfiguration: 
          Status: Enabled
      WebsiteConfiguration: 
          IndexDocument: !Sub 
            - '${Environment}.html'
            - Environment: !Ref Env

  "BucketPolicy":
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref bucket
      PolicyDocument:
        Id: 1
        Version: '2012-10-17'
        Statement:
          - Action: 's3:GetObject'
            Effect: Allow
            Principal: '*'
            Resource: !Sub 'arn:aws:s3:::${bucket}/*'
